---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service-b
  namespace: default
  labels:
    k8s-app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: service-b
  template:
    metadata:
      name: service-b
      creationTimestamp: 
      labels:
        k8s-app: service-b
    spec:
      containers:
      - name: service-b
        image: demo/service-b
        env:
        - name: JAVA_OPTS
          value: "-Dspring.cloud.config.uri=http://service-config:8888"
        resources: {}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 10
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
---
kind: Service
apiVersion: v1
metadata:
  name: service-b
  namespace: default
  labels:
    k8s-app: service-b
spec:
  ports:
  - name: service-b
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30003
  selector:
    k8s-app: service-b
  type: NodePort
