---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service-config
  namespace: default
  labels:
    k8s-app: service-config
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: service-config
  template:
    metadata:
      name: service-config
      creationTimestamp: 
      labels:
        k8s-app: service-config
    spec:
      containers:
      - name: service-config
        image: demo/service-config
        env:
        - name: JAVA_OPTS
          value: "-Dspring.cloud.config.uri=http://service-config:8888"
        resources: {}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
---
kind: Service
apiVersion: v1
metadata:
  name: service-config
  namespace: default
  labels:
    k8s-app: service-config
spec:
  ports:
  - name: service-config
    protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30001
  selector:
    k8s-app: service-config
  type: NodePort
