---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service-a
  namespace: default
  labels:
    k8s-app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: service-a
  template:
    metadata:
      name: service-a
      creationTimestamp: 
      labels:
        k8s-app: service-a
    spec:
      containers:
      - name: service-a
        image: demo/service-a
        env:
        - name: JAVA_OPTS
          value: "-Dspring.cloud.config.uri=http://config-service:8888"
        resources: {}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
---
kind: Service
apiVersion: v1
metadata:
  name: service-a
  namespace: default
  labels:
    k8s-app: service-a
spec:
  ports:
  - name: service-a
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30002
  selector:
    k8s-app: service-a
  type: NodePort
